server:
  port: 3333
  compression:
    enabled: true
    mime-types: "application/json,application/xml,text/html,text/xml,text/plain"
  tomcat:
    compression: on
    compressable-mime-types: "application/json,application/xml,text/html,text/xml,text/plain"

cassandra:
  contact-points: "cassandra"
  keyspace: "custom_field_test"
  port: 9042

spring:
  jackson:
    property-naming-strategy: "CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES"
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_empty